Repository Five-Crowns/Minitwit_Crown, pull requests merged in 2025-02, with the labels that each got.

#16 Fix user profiles
  Logbook.md
  minitwit.rb
Labels: bug-fixing

#17 Fixed follow and unfollow
  Logbook.md
  minitwit.rb
Labels: bug-fixing

#20 Refactored Python Test Suite to Ruby Using RSpec
  .gitignore
  Gemfile
  Gemfile.lock
  Logbook.md
  Test/minitwit_tests_spec.rb
  __pycache__/refactored_minitwit_tests.cpython-312-pytest-8.3.4.pyc
  minitwit.db
  minitwit.rb
  views/timeline.erb
Labels: bug-fixing, documentation, enhancement

#21 In memory testing
  Endpoints/database.rb
  Logbook.md
  Test/minitwit_tests_spec.rb
Labels: enhancement

#22 Revert "In memory testing"
  Endpoints/database.rb
  Logbook.md
  Test/minitwit_tests_spec.rb
Labels: bug-fixing

#27 Decently sized rewrite/cleanup, also added a lot of code documentation
  .gitignore
  Endpoints/database.rb
  Endpoints/endpoint_methods.rb
  Endpoints/endpoints_api.rb
  Endpoints/endpoints_html.rb
  Test/minitwit_sim_api_test.py
  compose.yaml
Labels: documentation, enhancement

#29 Cloud deployment to Digital Ocean.
  Dockerfile
  Dockerfile.app
  Logbook.md
  Vagrantfile
  compose.yaml
  docker-compose.yml
  flag_tool
  flag_tool.c
  minitwit.db
  remote_files/deploy.sh
  remote_files/docker-compose.yml
Labels: enhancement

#28 Created continous-deployment.yml
  .github/workflows/continous-deployment.yml
Labels: enhancement
