Repository Five-Crowns/Minitwit_Crown, pull requests merged in 2025-03, with the labels that each got.

#38 Add conditional execution for SSH configuration and deployment steps for worfklow
  .github/workflows/continous-deployment.yml
  .github/workflows/continous-testing.yml
  .gitignore
  Endpoints/endpoints_api.rb
  Test/minitwit_sim_api_test.py
  docker-compose.local.yml
  minitwit.rb
Labels: bug-fixing, enhancement

#41 Adjusted workflow run events
  .github/workflows/continous-deployment.yml
  .github/workflows/continous-testing.yml
Labels: enhancement

#53 Im not having fun
  .github/workflows/continous-testing.yml
  .gitignore
  Endpoints/endpoint_methods.rb
  Endpoints/endpoints_api.rb
  Endpoints/endpoints_html.rb
  Gemfile
  Gemfile.lock
  Rakefile.rb
  Test/minitwit_tests_spec.rb
  Test/run_tests.sh
  Vagrantfile
  db_config.rb
  docker-compose.test.yml
  metrics.rb
  minitwit.rb
  models/follower.rb
  models/message.rb
  models/user.rb
Labels: documentation, enhancement

#58 renamed workflows
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
Labels: enhancement

#64 Refactor pg tables
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  Dockerfile.app
  Endpoints/endpoint_methods.rb
  Endpoints/endpoints_html.rb
  db/migrate/20250306222930_create_users.rb
  db/migrate/20250306222942_create_messages.rb
  docker-compose.yml
Labels: enhancement

#65 UI Tests
  Dockerfile.test
  Gemfile
  Test/minitwit_tests_ui.rb
  Test/run_tests.sh
Labels: testing

#67 Baked in environment variables
  .github/workflows/continuous-deployment.yml
  Dockerfile.app
  docker-compose.yml
Labels: enhancement
